name: frontend
description: A new Flutter project.

publish_to: 'none'

version: 0.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  functional_widget_annotation: ^0.10.0
  hooks_riverpod: ^1.0.3

dev_dependencies:
  analyzer: ^4.0.0
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  functional_widget: ^0.10.0

flutter:
  uses-material-design: true
