/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/parse": {
    /** validate username & password and return a token. */
    post: {
      responses: {
        /** success */
        200: {
          content: {
            "text/plain": string;
          };
        };
        /** failure */
        401: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            username: string;
            /** Format: password */
            password: string;
          };
        };
      };
    };
  };
  "/validate": {
    /** validate a token & return the userId */
    post: {
      responses: {
        /** success */
        200: {
          content: {
            "text/plain": string;
          };
        };
        /** failure */
        401: unknown;
      };
      requestBody: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
}

export interface components {}

export interface operations {}

export interface external {}
