name: auth
on:
  push:
    paths:
    - 'backend/auth/**/*'
  pull_request:
defaults:
  run:
    working-directory: ./backend/auth
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn
    - run: yarn prisma-gen
    - run: yarn build
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn
    - run: yarn prisma-gen
    - run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn
    - run: yarn prisma-gen
    - run: yarn test
