name: notif
on:
  push:
    paths:
    - 'backend/notif/**/*'
  pull_request:
defaults:
  run:
    working-directory: ./backend/notif
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./backend/notif/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('./backend/notif/Cargo.lock') }}
    - run: cargo check
  clippy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./backend/notif/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('./backend/notif/Cargo.lock') }}
    - run: cargo clippy -- -D warnings
  fmt:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./backend/notif/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('./backend/notif/Cargo.lock') }}
    - run: cargo fmt --all -- --check
