name: rest
on:
  push:
    paths:
    - 'backend/rest/**/*'
  pull_request:
defaults:
  run:
    working-directory: ./backend/rest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - id: cache-yarn
      uses: actions/cache@v3
      with:
        path: ./backend/rest/.yarn/unplugged/
        key: ${{ runner.os }}-cargo-${{ hashFiles('./backend/rest/yarn.lock') }}
    - if: steps.cache-yarn.outputs.cache-hit != 'true'
      run: yarn
    - id: cache-prisma
      uses: actions/cache@v3
      with:
        path: ./backend/rest/prisma/
        key: ${{ runner.os }}-cargo-${{ hashFiles('./backend/rest/prisma/schema.prisma') }}
    - if: steps.cache-prisma.outputs.cache-hit != 'true'
      run: yarn prisma-gen
    - run: yarn build
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - id: cache-yarn
      uses: actions/cache@v3
      with:
        path: ./backend/rest/.yarn/unplugged/
        key: ${{ runner.os }}-cargo-${{ hashFiles('./backend/rest/yarn.lock') }}
    - if: steps.cache-yarn.outputs.cache-hit != 'true'
      run: yarn
    - id: cache-prisma
      uses: actions/cache@v3
      with:
        path: ./backend/rest/prisma/
        key: ${{ runner.os }}-cargo-${{ hashFiles('./backend/rest/prisma/schema.prisma') }}
    - if: steps.cache-prisma.outputs.cache-hit != 'true'
      run: yarn prisma-gen
    - run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - id: cache-yarn
      uses: actions/cache@v3
      with:
        path: ./backend/rest/.yarn/unplugged/
        key: ${{ runner.os }}-cargo-${{ hashFiles('./backend/rest/yarn.lock') }}
    - if: steps.cache-yarn.outputs.cache-hit != 'true'
      run: yarn
    - id: cache-prisma
      uses: actions/cache@v3
      with:
        path: ./backend/rest/prisma/
        key: ${{ runner.os }}-cargo-${{ hashFiles('./backend/rest/prisma/schema.prisma') }}
    - if: steps.cache-prisma.outputs.cache-hit != 'true'
      run: yarn prisma-gen
    - run: yarn test
