name: rest
on:
  push:
    paths:
    - 'backend/rest/**/*'
defaults:
  run:
    working-directory: ./backend/rest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install -g yarn
    - run: yarn
    - run: yarn prisma-gen
    - run: yarn build
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install -g yarn
    - run: yarn
    - run: yarn prisma-gen
    - run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install -g yarn
    - run: yarn
    - run: yarn prisma-gen
    - run: yarn test
